---

# 1. install and setup dotfiles

- name: install dotfiles
  git:
    repo: 'https://github.com/HiromuMasuda/dotfiles.git'
    clone: no
    dest: ~/

- name: add link to dotfiles
  file:
    src: '~/dotfiles/{{ item.filename }}'
    dest: '~/{{ item.filename }}'
    state: link
  with_items:
    - { filename: '.vimrc' }
    - { filename: '.tmux.conf' }
    - { filename: '.gitconfig' }


# 2. setup vimrc

- name: Download dein installer file
  get_url:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: /tmp/installer.sh

- name: run dein installer
  command: sh /tmp/installer.sh ~/.cache/dein


# 3. setup .tmux.conf


# 4. setup python

- name: setup python
  shell: |
    brew install pyenv
    pyenv install anaconda3-5.0.1
    pyenv global anaconda3-5.0.1


# 5. setup fish

- name: install and setup fish
  shell: |
    brew install fish
    sudo echo /usr/local/bin/fish >> /etc/shells
    chsh -s /usr/local/bin/fish
